# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SkjermProg.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(620, 423)
        self.Test2 = QtWidgets.QPushButton(Form)
        self.Test2.setGeometry(QtCore.QRect(130, 360, 111, 61))
        self.Test2.setObjectName("Test2")
        self.Test1 = QtWidgets.QPushButton(Form)
        self.Test1.setGeometry(QtCore.QRect(0, 360, 131, 61))
        self.Test1.setObjectName("Test1")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 191, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_01 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_01.setObjectName("label_01")
        self.gridLayout.addWidget(self.label_01, 1, 0, 1, 1)
        self.label_04 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_04.setObjectName("label_04")
        self.gridLayout.addWidget(self.label_04, 1, 2, 1, 1)
        self.label_02 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_02.setObjectName("label_02")
        self.gridLayout.addWidget(self.label_02, 2, 0, 1, 1)
        self.label_05 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_05.setObjectName("label_05")
        self.gridLayout.addWidget(self.label_05, 2, 2, 1, 1)
        self.label_06 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_06.setObjectName("label_06")
        self.gridLayout.addWidget(self.label_06, 3, 2, 1, 1)
        self.label_03 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_03.setObjectName("label_03")
        self.gridLayout.addWidget(self.label_03, 3, 0, 1, 1)
        self.label_07 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_07.setObjectName("label_07")
        self.gridLayout.addWidget(self.label_07, 3, 1, 1, 1)
        self.Label_08 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_08.setObjectName("Label_08")
        self.gridLayout.addWidget(self.Label_08, 2, 1, 1, 1)
        self.Test3 = QtWidgets.QPushButton(Form)
        self.Test3.setGeometry(QtCore.QRect(240, 360, 111, 61))
        self.Test3.setObjectName("Test3")
        self.Background = QtWidgets.QLabel(Form)
        self.Background.setEnabled(False)
        self.Background.setGeometry(QtCore.QRect(6, 2, 561, 391))
        self.Background.setObjectName("Background")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(200, 10, 201, 181))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 1, 1, 1)
        self.Label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Label_18.setObjectName("Label_18")
        self.gridLayout_2.addWidget(self.Label_18, 2, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(400, 10, 201, 181))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 3, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 3, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 3, 1, 1, 1)
        self.Label_19 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.Label_19.setObjectName("Label_19")
        self.gridLayout_3.addWidget(self.Label_19, 2, 1, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 190, 191, 171))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 1, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 2, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 2, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 3, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 3, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 3, 1, 1, 1)
        self.Label_20 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.Label_20.setObjectName("Label_20")
        self.gridLayout_4.addWidget(self.Label_20, 2, 1, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(200, 190, 201, 171))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 1, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 1, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 2, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 3, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 3, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 3, 1, 1, 1)
        self.Label_21 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.Label_21.setObjectName("Label_21")
        self.gridLayout_5.addWidget(self.Label_21, 2, 1, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(400, 190, 201, 171))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_51.setObjectName("label_51")
        self.gridLayout_6.addWidget(self.label_51, 1, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_54.setObjectName("label_54")
        self.gridLayout_6.addWidget(self.label_54, 1, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_52.setObjectName("label_52")
        self.gridLayout_6.addWidget(self.label_52, 2, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 2, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_53.setObjectName("label_53")
        self.gridLayout_6.addWidget(self.label_53, 3, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 3, 1, 1, 1)
        self.Label_22 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.Label_22.setObjectName("Label_22")
        self.gridLayout_6.addWidget(self.Label_22, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 3, 2, 1, 1)
        self.Background.raise_()
        self.Test2.raise_()
        self.Test1.raise_()
        self.gridLayoutWidget.raise_()
        self.Test3.raise_()
        self.gridLayoutWidget_2.raise_()
        self.gridLayoutWidget_3.raise_()
        self.gridLayoutWidget_4.raise_()
        self.gridLayoutWidget_5.raise_()
        self.gridLayoutWidget_6.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Test2.setText(_translate("Form", "Test 2"))
        self.Test1.setText(_translate("Form", "Test 1"))
        self.label_01.setText(_translate("Form", "Label_01"))
        self.label_04.setText(_translate("Form", "Label_04"))
        self.label_02.setText(_translate("Form", "Label_02"))
        self.label_05.setText(_translate("Form", "Label_05"))
        self.label_06.setText(_translate("Form", "Label_06"))
        self.label_03.setText(_translate("Form", "Labe_03"))
        self.label_07.setText(_translate("Form", "Label_07"))
        self.Label_08.setText(_translate("Form", "L1"))
        self.Test3.setText(_translate("Form", "Test 3"))
        self.Background.setText(_translate("Form", "Background"))
        self.label_11.setText(_translate("Form", "Label_11"))
        self.label_14.setText(_translate("Form", "Label_14"))
        self.label_12.setText(_translate("Form", "Label_12"))
        self.label_15.setText(_translate("Form", "Label_15"))
        self.label_16.setText(_translate("Form", "Label_16"))
        self.label_13.setText(_translate("Form", "Labe_13"))
        self.label_17.setText(_translate("Form", "Label_17"))
        self.Label_18.setText(_translate("Form", "L2"))
        self.label_21.setText(_translate("Form", "Label_21"))
        self.label_24.setText(_translate("Form", "Label_24"))
        self.label_22.setText(_translate("Form", "Label_22"))
        self.label_25.setText(_translate("Form", "Label_25"))
        self.label_26.setText(_translate("Form", "Label_26"))
        self.label_23.setText(_translate("Form", "Labe_23"))
        self.label_27.setText(_translate("Form", "Label_27"))
        self.Label_19.setText(_translate("Form", "L3"))
        self.label_31.setText(_translate("Form", "Label_31"))
        self.label_34.setText(_translate("Form", "Label_34"))
        self.label_32.setText(_translate("Form", "Label_32"))
        self.label_35.setText(_translate("Form", "Label_35"))
        self.label_36.setText(_translate("Form", "Label_36"))
        self.label_33.setText(_translate("Form", "Labe_33"))
        self.label_37.setText(_translate("Form", "Label_37"))
        self.Label_20.setText(_translate("Form", "R1"))
        self.label_41.setText(_translate("Form", "Label_41"))
        self.label_44.setText(_translate("Form", "Label_44"))
        self.label_42.setText(_translate("Form", "Label_42"))
        self.label_45.setText(_translate("Form", "Label_45"))
        self.label_46.setText(_translate("Form", "Label_46"))
        self.label_43.setText(_translate("Form", "Labe_43"))
        self.label_47.setText(_translate("Form", "Label_47"))
        self.Label_21.setText(_translate("Form", "R2"))
        self.label_51.setText(_translate("Form", "Label_51"))
        self.label_54.setText(_translate("Form", "Label_54"))
        self.label_52.setText(_translate("Form", "Label_52"))
        self.label_55.setText(_translate("Form", "Label_55"))
        self.label_53.setText(_translate("Form", "Labe_53"))
        self.label_57.setText(_translate("Form", "Label_57"))
        self.Label_22.setText(_translate("Form", "R3"))
        self.label_56.setText(_translate("Form", "Label_56"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

