# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skjerm.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(800, 480)
        Form.setMinimumSize(QtCore.QSize(800, 480))
        Form.setMaximumSize(QtCore.QSize(800, 480))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.gridFrame_7 = QtWidgets.QFrame(Form)
        self.gridFrame_7.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.gridFrame_7.setMinimumSize(QtCore.QSize(800, 480))
        self.gridFrame_7.setMaximumSize(QtCore.QSize(800, 480))
        self.gridFrame_7.setObjectName("gridFrame_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridFrame_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Test = QtWidgets.QPushButton(self.gridFrame_7)
        self.Test.setEnabled(True)
        self.Test.setMinimumSize(QtCore.QSize(135, 55))
        self.Test.setMaximumSize(QtCore.QSize(135, 55))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.Test.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Test.setFont(font)
        self.Test.setAutoFillBackground(False)
        self.Test.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.Test.setObjectName("Test")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Test)
        self.Reset = QtWidgets.QPushButton(self.gridFrame_7)
        self.Reset.setEnabled(True)
        self.Reset.setMinimumSize(QtCore.QSize(135, 55))
        self.Reset.setMaximumSize(QtCore.QSize(135, 55))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Reset.setFont(font)
        self.Reset.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Reset.setAutoFillBackground(False)
        self.Reset.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.Reset.setCheckable(False)
        self.Reset.setAutoDefault(False)
        self.Reset.setObjectName("Reset")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Reset)
        self.label_3 = QtWidgets.QLabel(self.gridFrame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.gridLayout_7.addLayout(self.formLayout, 1, 2, 1, 1)
        self.gridFrame = QtWidgets.QFrame(self.gridFrame_7)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(10, 4, -1, 0)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_01 = QtWidgets.QLabel(self.gridFrame)
        self.label_01.setObjectName("label_01")
        self.gridLayout.addWidget(self.label_01, 0, 0, 1, 1)
        self.label_02 = QtWidgets.QLabel(self.gridFrame)
        self.label_02.setObjectName("label_02")
        self.gridLayout.addWidget(self.label_02, 1, 0, 1, 1)
        self.label_03 = QtWidgets.QLabel(self.gridFrame)
        self.label_03.setObjectName("label_03")
        self.gridLayout.addWidget(self.label_03, 2, 0, 1, 1)
        self.label_07 = QtWidgets.QLabel(self.gridFrame)
        self.label_07.setObjectName("label_07")
        self.gridLayout.addWidget(self.label_07, 2, 1, 1, 1)
        self.label_06 = QtWidgets.QLabel(self.gridFrame)
        self.label_06.setObjectName("label_06")
        self.gridLayout.addWidget(self.label_06, 2, 2, 1, 1)
        self.label_04 = QtWidgets.QLabel(self.gridFrame)
        self.label_04.setObjectName("label_04")
        self.gridLayout.addWidget(self.label_04, 0, 2, 1, 1)
        self.label_05 = QtWidgets.QLabel(self.gridFrame)
        self.label_05.setObjectName("label_05")
        self.gridLayout.addWidget(self.label_05, 1, 2, 1, 1)
        self.label_08 = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_08.setFont(font)
        self.label_08.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_08.setTextFormat(QtCore.Qt.AutoText)
        self.label_08.setScaledContents(False)
        self.label_08.setObjectName("label_08")
        self.gridLayout.addWidget(self.label_08, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.gridFrame, 0, 0, 1, 1)
        self.gridFrame_10 = QtWidgets.QFrame(self.gridFrame_7)
        self.gridFrame_10.setMinimumSize(QtCore.QSize(155, 155))
        self.gridFrame_10.setMaximumSize(QtCore.QSize(155, 155))
        self.gridFrame_10.setObjectName("gridFrame_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridFrame_10)
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_10.setContentsMargins(10, 3, -1, 12)
        self.gridLayout_10.setHorizontalSpacing(12)
        self.gridLayout_10.setVerticalSpacing(8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lab_25 = QtWidgets.QLabel(self.gridFrame_10)
        self.lab_25.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_25.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_25.setObjectName("lab_25")
        self.gridLayout_10.addWidget(self.lab_25, 1, 2, 1, 1)
        self.lab_28 = QtWidgets.QLabel(self.gridFrame_10)
        self.lab_28.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_28.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_28.setObjectName("lab_28")
        self.gridLayout_10.addWidget(self.lab_28, 2, 1, 1, 1)
        self.lab_22 = QtWidgets.QLabel(self.gridFrame_10)
        self.lab_22.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_22.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_22.setObjectName("lab_22")
        self.gridLayout_10.addWidget(self.lab_22, 0, 1, 1, 1)
        self.lab_23 = QtWidgets.QLabel(self.gridFrame_10)
        self.lab_23.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_23.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_23.setObjectName("lab_23")
        self.gridLayout_10.addWidget(self.lab_23, 0, 2, 1, 1)
        self.lab_27 = QtWidgets.QLabel(self.gridFrame_10)
        self.lab_27.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_27.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_27.setObjectName("lab_27")
        self.gridLayout_10.addWidget(self.lab_27, 2, 0, 1, 1)
        self.lab_24 = QtWidgets.QLabel(self.gridFrame_10)
        self.lab_24.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_24.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_24.setObjectName("lab_24")
        self.gridLayout_10.addWidget(self.lab_24, 1, 0, 1, 1)
        self.lab_21 = QtWidgets.QLabel(self.gridFrame_10)
        self.lab_21.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_21.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_21.setObjectName("lab_21")
        self.gridLayout_10.addWidget(self.lab_21, 0, 0, 1, 1)
        self.lab_29 = QtWidgets.QLabel(self.gridFrame_10)
        self.lab_29.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_29.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_29.setObjectName("lab_29")
        self.gridLayout_10.addWidget(self.lab_29, 2, 2, 1, 1)
        self.lab_26 = QtWidgets.QLabel(self.gridFrame_10)
        self.lab_26.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_26.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_26.setObjectName("lab_26")
        self.gridLayout_10.addWidget(self.lab_26, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.gridFrame_10, 2, 2, 1, 1)
        self.gridFrame_6 = QtWidgets.QFrame(self.gridFrame_7)
        self.gridFrame_6.setMinimumSize(QtCore.QSize(155, 155))
        self.gridFrame_6.setMaximumSize(QtCore.QSize(155, 155))
        self.gridFrame_6.setObjectName("gridFrame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridFrame_6)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setContentsMargins(10, 3, -1, 12)
        self.gridLayout_6.setHorizontalSpacing(12)
        self.gridLayout_6.setVerticalSpacing(8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_55 = QtWidgets.QLabel(self.gridFrame_6)
        self.label_55.setMinimumSize(QtCore.QSize(50, 50))
        self.label_55.setMaximumSize(QtCore.QSize(50, 50))
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 2, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridFrame_6)
        self.label_52.setMinimumSize(QtCore.QSize(50, 50))
        self.label_52.setMaximumSize(QtCore.QSize(50, 50))
        self.label_52.setObjectName("label_52")
        self.gridLayout_6.addWidget(self.label_52, 2, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridFrame_6)
        self.label_53.setMinimumSize(QtCore.QSize(50, 50))
        self.label_53.setMaximumSize(QtCore.QSize(50, 50))
        self.label_53.setObjectName("label_53")
        self.gridLayout_6.addWidget(self.label_53, 3, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridFrame_6)
        self.label_57.setMinimumSize(QtCore.QSize(50, 50))
        self.label_57.setMaximumSize(QtCore.QSize(50, 50))
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 3, 1, 1, 1)
        self.Label_22 = QtWidgets.QLabel(self.gridFrame_6)
        self.Label_22.setMinimumSize(QtCore.QSize(50, 50))
        self.Label_22.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Label_22.setFont(font)
        self.Label_22.setObjectName("Label_22")
        self.gridLayout_6.addWidget(self.Label_22, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridFrame_6)
        self.label_56.setMinimumSize(QtCore.QSize(50, 50))
        self.label_56.setMaximumSize(QtCore.QSize(50, 50))
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 3, 2, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridFrame_6)
        self.label_54.setMinimumSize(QtCore.QSize(50, 50))
        self.label_54.setMaximumSize(QtCore.QSize(50, 50))
        self.label_54.setObjectName("label_54")
        self.gridLayout_6.addWidget(self.label_54, 1, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridFrame_6)
        self.label_51.setMinimumSize(QtCore.QSize(50, 50))
        self.label_51.setMaximumSize(QtCore.QSize(50, 50))
        self.label_51.setObjectName("label_51")
        self.gridLayout_6.addWidget(self.label_51, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gridFrame_6, 2, 4, 1, 1)
        self.gridFrame_5 = QtWidgets.QFrame(self.gridFrame_7)
        self.gridFrame_5.setMinimumSize(QtCore.QSize(155, 155))
        self.gridFrame_5.setMaximumSize(QtCore.QSize(155, 155))
        self.gridFrame_5.setObjectName("gridFrame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridFrame_5)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setContentsMargins(10, 3, -1, 12)
        self.gridLayout_5.setHorizontalSpacing(12)
        self.gridLayout_5.setVerticalSpacing(8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_41 = QtWidgets.QLabel(self.gridFrame_5)
        self.label_41.setMinimumSize(QtCore.QSize(50, 50))
        self.label_41.setMaximumSize(QtCore.QSize(50, 50))
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 1, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridFrame_5)
        self.label_44.setMinimumSize(QtCore.QSize(50, 50))
        self.label_44.setMaximumSize(QtCore.QSize(50, 50))
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 1, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridFrame_5)
        self.label_42.setMinimumSize(QtCore.QSize(50, 50))
        self.label_42.setMaximumSize(QtCore.QSize(50, 50))
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridFrame_5)
        self.label_45.setMinimumSize(QtCore.QSize(50, 50))
        self.label_45.setMaximumSize(QtCore.QSize(50, 50))
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 2, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridFrame_5)
        self.label_46.setMinimumSize(QtCore.QSize(50, 50))
        self.label_46.setMaximumSize(QtCore.QSize(50, 50))
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 3, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridFrame_5)
        self.label_43.setMinimumSize(QtCore.QSize(50, 50))
        self.label_43.setMaximumSize(QtCore.QSize(50, 50))
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 3, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gridFrame_5)
        self.label_47.setMinimumSize(QtCore.QSize(50, 50))
        self.label_47.setMaximumSize(QtCore.QSize(50, 50))
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 3, 1, 1, 1)
        self.Label_21 = QtWidgets.QLabel(self.gridFrame_5)
        self.Label_21.setMinimumSize(QtCore.QSize(50, 50))
        self.Label_21.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Label_21.setFont(font)
        self.Label_21.setObjectName("Label_21")
        self.gridLayout_5.addWidget(self.Label_21, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.gridFrame_5, 1, 4, 1, 1)
        self.gridFrame_2 = QtWidgets.QFrame(self.gridFrame_7)
        self.gridFrame_2.setMinimumSize(QtCore.QSize(155, 155))
        self.gridFrame_2.setMaximumSize(QtCore.QSize(155, 155))
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(10, 3, -1, 12)
        self.gridLayout_2.setHorizontalSpacing(12)
        self.gridLayout_2.setVerticalSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_15.setMinimumSize(QtCore.QSize(50, 50))
        self.label_15.setMaximumSize(QtCore.QSize(50, 50))
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_11.setMinimumSize(QtCore.QSize(50, 50))
        self.label_11.setMaximumSize(QtCore.QSize(50, 50))
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_16.setMinimumSize(QtCore.QSize(50, 50))
        self.label_16.setMaximumSize(QtCore.QSize(50, 50))
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_12.setMinimumSize(QtCore.QSize(50, 50))
        self.label_12.setMaximumSize(QtCore.QSize(50, 50))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_13.setMinimumSize(QtCore.QSize(50, 50))
        self.label_13.setMaximumSize(QtCore.QSize(50, 50))
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_14.setMinimumSize(QtCore.QSize(50, 50))
        self.label_14.setMaximumSize(QtCore.QSize(50, 50))
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 2, 1, 1)
        self.Label_18 = QtWidgets.QLabel(self.gridFrame_2)
        self.Label_18.setMinimumSize(QtCore.QSize(50, 50))
        self.Label_18.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Label_18.setFont(font)
        self.Label_18.setObjectName("Label_18")
        self.gridLayout_2.addWidget(self.Label_18, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_17.setMinimumSize(QtCore.QSize(50, 50))
        self.label_17.setMaximumSize(QtCore.QSize(50, 50))
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 1, 1, 1)
        self.gridLayout_7.addWidget(self.gridFrame_2, 1, 0, 1, 1)
        self.gridFrame_9 = QtWidgets.QFrame(self.gridFrame_7)
        self.gridFrame_9.setMinimumSize(QtCore.QSize(155, 155))
        self.gridFrame_9.setMaximumSize(QtCore.QSize(155, 155))
        self.gridFrame_9.setObjectName("gridFrame_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridFrame_9)
        self.gridLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_9.setContentsMargins(10, 3, -1, 12)
        self.gridLayout_9.setHorizontalSpacing(12)
        self.gridLayout_9.setVerticalSpacing(8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lab_2 = QtWidgets.QLabel(self.gridFrame_9)
        self.lab_2.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_2.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_2.setObjectName("lab_2")
        self.gridLayout_9.addWidget(self.lab_2, 0, 1, 1, 1)
        self.lab_5 = QtWidgets.QLabel(self.gridFrame_9)
        self.lab_5.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_5.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_5.setObjectName("lab_5")
        self.gridLayout_9.addWidget(self.lab_5, 1, 1, 1, 1)
        self.lab_8 = QtWidgets.QLabel(self.gridFrame_9)
        self.lab_8.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_8.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_8.setObjectName("lab_8")
        self.gridLayout_9.addWidget(self.lab_8, 2, 1, 1, 1)
        self.lab_1 = QtWidgets.QLabel(self.gridFrame_9)
        self.lab_1.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_1.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_1.setObjectName("lab_1")
        self.gridLayout_9.addWidget(self.lab_1, 0, 2, 1, 1)
        self.lab_3 = QtWidgets.QLabel(self.gridFrame_9)
        self.lab_3.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_3.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_3.setObjectName("lab_3")
        self.gridLayout_9.addWidget(self.lab_3, 0, 0, 1, 1)
        self.lab_4 = QtWidgets.QLabel(self.gridFrame_9)
        self.lab_4.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_4.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_4.setObjectName("lab_4")
        self.gridLayout_9.addWidget(self.lab_4, 1, 2, 1, 1)
        self.lab_6 = QtWidgets.QLabel(self.gridFrame_9)
        self.lab_6.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_6.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_6.setObjectName("lab_6")
        self.gridLayout_9.addWidget(self.lab_6, 1, 0, 1, 1)
        self.lab_9 = QtWidgets.QLabel(self.gridFrame_9)
        self.lab_9.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_9.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_9.setObjectName("lab_9")
        self.gridLayout_9.addWidget(self.lab_9, 2, 0, 1, 1)
        self.lab_7 = QtWidgets.QLabel(self.gridFrame_9)
        self.lab_7.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_7.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_7.setObjectName("lab_7")
        self.gridLayout_9.addWidget(self.lab_7, 2, 2, 1, 1)
        self.gridLayout_7.addWidget(self.gridFrame_9, 2, 1, 1, 1)
        self.gridFrame_4 = QtWidgets.QFrame(self.gridFrame_7)
        self.gridFrame_4.setMinimumSize(QtCore.QSize(155, 155))
        self.gridFrame_4.setMaximumSize(QtCore.QSize(155, 155))
        self.gridFrame_4.setObjectName("gridFrame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridFrame_4)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(10, 3, -1, 12)
        self.gridLayout_4.setHorizontalSpacing(12)
        self.gridLayout_4.setVerticalSpacing(8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_31 = QtWidgets.QLabel(self.gridFrame_4)
        self.label_31.setMinimumSize(QtCore.QSize(50, 50))
        self.label_31.setMaximumSize(QtCore.QSize(50, 50))
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridFrame_4)
        self.label_34.setMinimumSize(QtCore.QSize(50, 50))
        self.label_34.setMaximumSize(QtCore.QSize(50, 50))
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 1, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridFrame_4)
        self.label_32.setMinimumSize(QtCore.QSize(50, 50))
        self.label_32.setMaximumSize(QtCore.QSize(50, 50))
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 2, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridFrame_4)
        self.label_35.setMinimumSize(QtCore.QSize(50, 50))
        self.label_35.setMaximumSize(QtCore.QSize(50, 50))
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 2, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridFrame_4)
        self.label_36.setMinimumSize(QtCore.QSize(50, 50))
        self.label_36.setMaximumSize(QtCore.QSize(50, 50))
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 3, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridFrame_4)
        self.label_33.setMinimumSize(QtCore.QSize(50, 50))
        self.label_33.setMaximumSize(QtCore.QSize(50, 50))
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 3, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridFrame_4)
        self.label_37.setMinimumSize(QtCore.QSize(50, 50))
        self.label_37.setMaximumSize(QtCore.QSize(50, 50))
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 3, 1, 1, 1)
        self.Label_20 = QtWidgets.QLabel(self.gridFrame_4)
        self.Label_20.setMinimumSize(QtCore.QSize(50, 50))
        self.Label_20.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Label_20.setFont(font)
        self.Label_20.setObjectName("Label_20")
        self.gridLayout_4.addWidget(self.Label_20, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.gridFrame_4, 0, 4, 1, 1)
        self.gridFrame_11 = QtWidgets.QFrame(self.gridFrame_7)
        self.gridFrame_11.setMinimumSize(QtCore.QSize(155, 155))
        self.gridFrame_11.setMaximumSize(QtCore.QSize(155, 155))
        self.gridFrame_11.setObjectName("gridFrame_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridFrame_11)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_11.setContentsMargins(10, 3, -1, 12)
        self.gridLayout_11.setHorizontalSpacing(12)
        self.gridLayout_11.setVerticalSpacing(8)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lab_12 = QtWidgets.QLabel(self.gridFrame_11)
        self.lab_12.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_12.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_12.setObjectName("lab_12")
        self.gridLayout_11.addWidget(self.lab_12, 0, 1, 1, 1)
        self.lab_15 = QtWidgets.QLabel(self.gridFrame_11)
        self.lab_15.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_15.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_15.setObjectName("lab_15")
        self.gridLayout_11.addWidget(self.lab_15, 1, 1, 1, 1)
        self.lab_18 = QtWidgets.QLabel(self.gridFrame_11)
        self.lab_18.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_18.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_18.setObjectName("lab_18")
        self.gridLayout_11.addWidget(self.lab_18, 2, 1, 1, 1)
        self.lab_13 = QtWidgets.QLabel(self.gridFrame_11)
        self.lab_13.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_13.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_13.setObjectName("lab_13")
        self.gridLayout_11.addWidget(self.lab_13, 0, 0, 1, 1)
        self.lab_11 = QtWidgets.QLabel(self.gridFrame_11)
        self.lab_11.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_11.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_11.setObjectName("lab_11")
        self.gridLayout_11.addWidget(self.lab_11, 0, 2, 1, 1)
        self.lab_14 = QtWidgets.QLabel(self.gridFrame_11)
        self.lab_14.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_14.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_14.setObjectName("lab_14")
        self.gridLayout_11.addWidget(self.lab_14, 1, 2, 1, 1)
        self.lab_16 = QtWidgets.QLabel(self.gridFrame_11)
        self.lab_16.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_16.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_16.setObjectName("lab_16")
        self.gridLayout_11.addWidget(self.lab_16, 1, 0, 1, 1)
        self.lab_17 = QtWidgets.QLabel(self.gridFrame_11)
        self.lab_17.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_17.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_17.setObjectName("lab_17")
        self.gridLayout_11.addWidget(self.lab_17, 2, 2, 1, 1)
        self.lab_19 = QtWidgets.QLabel(self.gridFrame_11)
        self.lab_19.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_19.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_19.setObjectName("lab_19")
        self.gridLayout_11.addWidget(self.lab_19, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gridFrame_11, 2, 3, 1, 1)
        self.gridFrame_3 = QtWidgets.QFrame(self.gridFrame_7)
        self.gridFrame_3.setMinimumSize(QtCore.QSize(155, 155))
        self.gridFrame_3.setMaximumSize(QtCore.QSize(155, 155))
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(10, 3, -1, 12)
        self.gridLayout_3.setHorizontalSpacing(12)
        self.gridLayout_3.setVerticalSpacing(8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_24 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_24.setMinimumSize(QtCore.QSize(50, 50))
        self.label_24.setMaximumSize(QtCore.QSize(50, 50))
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_21.setMinimumSize(QtCore.QSize(50, 50))
        self.label_21.setMaximumSize(QtCore.QSize(50, 50))
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_26.setMinimumSize(QtCore.QSize(50, 50))
        self.label_26.setMaximumSize(QtCore.QSize(50, 50))
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 3, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_25.setMinimumSize(QtCore.QSize(50, 50))
        self.label_25.setMaximumSize(QtCore.QSize(50, 50))
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_27.setMinimumSize(QtCore.QSize(50, 50))
        self.label_27.setMaximumSize(QtCore.QSize(50, 50))
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 3, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_22.setMinimumSize(QtCore.QSize(50, 50))
        self.label_22.setMaximumSize(QtCore.QSize(50, 50))
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridFrame_3)
        self.label_23.setMinimumSize(QtCore.QSize(50, 50))
        self.label_23.setMaximumSize(QtCore.QSize(50, 50))
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 3, 0, 1, 1)
        self.Label_19 = QtWidgets.QLabel(self.gridFrame_3)
        self.Label_19.setMinimumSize(QtCore.QSize(50, 50))
        self.Label_19.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Label_19.setFont(font)
        self.Label_19.setObjectName("Label_19")
        self.gridLayout_3.addWidget(self.Label_19, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.gridFrame_3, 2, 0, 1, 1)
        self.gridFrame_15 = QtWidgets.QFrame(self.gridFrame_7)
        self.gridFrame_15.setMinimumSize(QtCore.QSize(155, 155))
        self.gridFrame_15.setMaximumSize(QtCore.QSize(155, 155))
        self.gridFrame_15.setObjectName("gridFrame_15")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gridFrame_15)
        self.gridLayout_16.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_16.setContentsMargins(10, 3, -1, 12)
        self.gridLayout_16.setHorizontalSpacing(12)
        self.gridLayout_16.setVerticalSpacing(8)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lab_32 = QtWidgets.QLabel(self.gridFrame_15)
        self.lab_32.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_32.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_32.setObjectName("lab_32")
        self.gridLayout_16.addWidget(self.lab_32, 0, 1, 1, 1)
        self.lab_31 = QtWidgets.QLabel(self.gridFrame_15)
        self.lab_31.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_31.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_31.setObjectName("lab_31")
        self.gridLayout_16.addWidget(self.lab_31, 0, 2, 1, 1)
        self.lab_33 = QtWidgets.QLabel(self.gridFrame_15)
        self.lab_33.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_33.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_33.setObjectName("lab_33")
        self.gridLayout_16.addWidget(self.lab_33, 0, 0, 1, 1)
        self.lab_34 = QtWidgets.QLabel(self.gridFrame_15)
        self.lab_34.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_34.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_34.setObjectName("lab_34")
        self.gridLayout_16.addWidget(self.lab_34, 2, 2, 1, 1)
        self.lab_37 = QtWidgets.QLabel(self.gridFrame_15)
        self.lab_37.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_37.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_37.setObjectName("lab_37")
        self.gridLayout_16.addWidget(self.lab_37, 3, 2, 1, 1)
        self.lab_36 = QtWidgets.QLabel(self.gridFrame_15)
        self.lab_36.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_36.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_36.setObjectName("lab_36")
        self.gridLayout_16.addWidget(self.lab_36, 2, 0, 1, 1)
        self.lab_35 = QtWidgets.QLabel(self.gridFrame_15)
        self.lab_35.setMinimumSize(QtCore.QSize(50, 50))
        self.lab_35.setMaximumSize(QtCore.QSize(50, 50))
        self.lab_35.setObjectName("lab_35")
        self.gridLayout_16.addWidget(self.lab_35, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridFrame_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_16.addWidget(self.label_4, 3, 1, 1, 1)
        self.gridLayout_7.addWidget(self.gridFrame_15, 0, 2, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(28, 5, 5, -1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_12.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.led_2 = QtWidgets.QLabel(self.gridFrame_7)
        self.led_2.setObjectName("led_2")
        self.gridLayout_12.addWidget(self.led_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridFrame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 2, 0, 1, 1)
        self.led_1 = QtWidgets.QLabel(self.gridFrame_7)
        self.led_1.setObjectName("led_1")
        self.gridLayout_12.addWidget(self.led_1, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_12, 1, 1, 1, 1)
        self.label_ = QtWidgets.QLabel(self.gridFrame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_.setFont(font)
        self.label_.setText("")
        self.label_.setObjectName("label_")
        self.gridLayout_7.addWidget(self.label_, 0, 3, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setContentsMargins(28, 5, 5, -1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_13.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridFrame_7)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_13.addWidget(self.label_6, 0, 0, 1, 1)
        self.led_3 = QtWidgets.QLabel(self.gridFrame_7)
        self.led_3.setObjectName("led_3")
        self.gridLayout_13.addWidget(self.led_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridFrame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_13.addWidget(self.label_5, 2, 0, 1, 1)
        self.led_4 = QtWidgets.QLabel(self.gridFrame_7)
        self.led_4.setObjectName("led_4")
        self.gridLayout_13.addWidget(self.led_4, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_13, 1, 3, 1, 1)
        self.gridFrame.raise_()
        self.gridFrame_2.raise_()
        self.gridFrame_3.raise_()
        self.gridFrame_4.raise_()
        self.gridFrame_5.raise_()
        self.gridFrame_6.raise_()
        self.gridFrame_9.raise_()
        self.gridFrame_10.raise_()
        self.gridFrame_11.raise_()
        self.gridFrame_15.raise_()
        self.label_.raise_()
        self.gridFrame_8 = QtWidgets.QFrame(Form)
        self.gridFrame_8.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.gridFrame_8.setMinimumSize(QtCore.QSize(800, 480))
        self.gridFrame_8.setMaximumSize(QtCore.QSize(800, 480))
        self.gridFrame_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.gridFrame_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridFrame_8.setObjectName("gridFrame_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridFrame_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.square_11 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_11.setMinimumSize(QtCore.QSize(155, 155))
        self.square_11.setMaximumSize(QtCore.QSize(155, 155))
        self.square_11.setObjectName("square_11")
        self.gridLayout_8.addWidget(self.square_11, 2, 3, 1, 1)
        self.square_6 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_6.setMinimumSize(QtCore.QSize(155, 155))
        self.square_6.setMaximumSize(QtCore.QSize(155, 155))
        self.square_6.setObjectName("square_6")
        self.gridLayout_8.addWidget(self.square_6, 0, 2, 1, 1)
        self.square_1 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_1.setMinimumSize(QtCore.QSize(155, 155))
        self.square_1.setMaximumSize(QtCore.QSize(155, 155))
        self.square_1.setObjectName("square_1")
        self.gridLayout_8.addWidget(self.square_1, 1, 0, 1, 1)
        self.square_10 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_10.setMinimumSize(QtCore.QSize(155, 155))
        self.square_10.setMaximumSize(QtCore.QSize(155, 155))
        self.square_10.setText("")
        self.square_10.setObjectName("square_10")
        self.gridLayout_8.addWidget(self.square_10, 1, 3, 1, 1)
        self.square_2 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_2.setMinimumSize(QtCore.QSize(155, 155))
        self.square_2.setMaximumSize(QtCore.QSize(155, 155))
        self.square_2.setObjectName("square_2")
        self.gridLayout_8.addWidget(self.square_2, 2, 0, 1, 1)
        self.square_7 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_7.setMinimumSize(QtCore.QSize(155, 155))
        self.square_7.setMaximumSize(QtCore.QSize(155, 155))
        self.square_7.setText("")
        self.square_7.setObjectName("square_7")
        self.gridLayout_8.addWidget(self.square_7, 1, 2, 1, 1)
        self.square_3 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_3.setMinimumSize(QtCore.QSize(155, 155))
        self.square_3.setMaximumSize(QtCore.QSize(155, 155))
        self.square_3.setObjectName("square_3")
        self.gridLayout_8.addWidget(self.square_3, 0, 1, 1, 1)
        self.square_8 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_8.setMinimumSize(QtCore.QSize(155, 155))
        self.square_8.setMaximumSize(QtCore.QSize(155, 155))
        self.square_8.setObjectName("square_8")
        self.gridLayout_8.addWidget(self.square_8, 2, 2, 1, 1)
        self.square_5 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_5.setMinimumSize(QtCore.QSize(155, 155))
        self.square_5.setMaximumSize(QtCore.QSize(155, 155))
        self.square_5.setObjectName("square_5")
        self.gridLayout_8.addWidget(self.square_5, 2, 1, 1, 1)
        self.square_14 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_14.setMinimumSize(QtCore.QSize(155, 155))
        self.square_14.setMaximumSize(QtCore.QSize(155, 155))
        self.square_14.setObjectName("square_14")
        self.gridLayout_8.addWidget(self.square_14, 2, 4, 1, 1)
        self.square_9 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_9.setMinimumSize(QtCore.QSize(155, 155))
        self.square_9.setMaximumSize(QtCore.QSize(155, 155))
        self.square_9.setObjectName("square_9")
        self.gridLayout_8.addWidget(self.square_9, 0, 3, 1, 1)
        self.square_12 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_12.setMinimumSize(QtCore.QSize(155, 155))
        self.square_12.setMaximumSize(QtCore.QSize(155, 155))
        self.square_12.setObjectName("square_12")
        self.gridLayout_8.addWidget(self.square_12, 0, 4, 1, 1)
        self.square_0 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_0.setMinimumSize(QtCore.QSize(155, 155))
        self.square_0.setMaximumSize(QtCore.QSize(155, 155))
        self.square_0.setObjectName("square_0")
        self.gridLayout_8.addWidget(self.square_0, 0, 0, 1, 1)
        self.square_13 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_13.setMinimumSize(QtCore.QSize(155, 155))
        self.square_13.setMaximumSize(QtCore.QSize(155, 155))
        self.square_13.setObjectName("square_13")
        self.gridLayout_8.addWidget(self.square_13, 1, 4, 1, 1)
        self.square_4 = QtWidgets.QLabel(self.gridFrame_8)
        self.square_4.setMinimumSize(QtCore.QSize(155, 155))
        self.square_4.setMaximumSize(QtCore.QSize(155, 155))
        self.square_4.setText("")
        self.square_4.setObjectName("square_4")
        self.gridLayout_8.addWidget(self.square_4, 1, 1, 1, 1)
        self.square_9.raise_()
        self.square_8.raise_()
        self.square_7.raise_()
        self.square_6.raise_()
        self.square_5.raise_()
        self.square_4.raise_()
        self.square_3.raise_()
        self.square_2.raise_()
        self.square_14.raise_()
        self.square_13.raise_()
        self.square_12.raise_()
        self.square_11.raise_()
        self.square_10.raise_()
        self.square_1.raise_()
        self.square_0.raise_()
        self.gridFrame_8.raise_()
        self.gridFrame_7.raise_()

        self.retranslateUi(Form)
        self.Test.clicked.connect(self.Test.hide)
        self.Test.clicked.connect(self.Reset.show)
        self.Reset.clicked.connect(self.Test.show)
        self.Reset.clicked.connect(self.Reset.hide)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Test.setText(_translate("Form", "Test"))
        self.Reset.setText(_translate("Form", "Reset"))
        self.label_3.setText(_translate("Form", "            PW"))
        self.label_01.setText(_translate("Form", "label_01"))
        self.label_02.setText(_translate("Form", "label_02"))
        self.label_03.setText(_translate("Form", "label_03"))
        self.label_07.setText(_translate("Form", "label_07"))
        self.label_06.setText(_translate("Form", "label_06"))
        self.label_04.setText(_translate("Form", "label_04"))
        self.label_05.setText(_translate("Form", "label_05"))
        self.label_08.setText(_translate("Form", " L1"))
        self.lab_25.setText(_translate("Form", "lab_25"))
        self.lab_28.setText(_translate("Form", "lab_28"))
        self.lab_22.setText(_translate("Form", "lab_22"))
        self.lab_23.setText(_translate("Form", "lab_23"))
        self.lab_27.setText(_translate("Form", "lab_27"))
        self.lab_24.setText(_translate("Form", "lab_24"))
        self.lab_21.setText(_translate("Form", "lab_21"))
        self.lab_29.setText(_translate("Form", "lab_29"))
        self.lab_26.setText(_translate("Form", "lab_26"))
        self.label_55.setText(_translate("Form", "Label_55"))
        self.label_52.setText(_translate("Form", "Label_52"))
        self.label_53.setText(_translate("Form", "Labe_53"))
        self.label_57.setText(_translate("Form", "Label_57"))
        self.Label_22.setText(_translate("Form", " R3"))
        self.label_56.setText(_translate("Form", "Label_56"))
        self.label_54.setText(_translate("Form", "Label_54"))
        self.label_51.setText(_translate("Form", "Label_51"))
        self.label_41.setText(_translate("Form", "Label_41"))
        self.label_44.setText(_translate("Form", "Label_44"))
        self.label_42.setText(_translate("Form", "Label_42"))
        self.label_45.setText(_translate("Form", "Label_45"))
        self.label_46.setText(_translate("Form", "Label_46"))
        self.label_43.setText(_translate("Form", "Labe_43"))
        self.label_47.setText(_translate("Form", "Label_47"))
        self.Label_21.setText(_translate("Form", " R2"))
        self.label_15.setText(_translate("Form", "Label_15"))
        self.label_11.setText(_translate("Form", "Label_11"))
        self.label_16.setText(_translate("Form", "Label_16"))
        self.label_12.setText(_translate("Form", "Label_12"))
        self.label_13.setText(_translate("Form", "Labe_13"))
        self.label_14.setText(_translate("Form", "Label_14"))
        self.Label_18.setText(_translate("Form", " L2"))
        self.label_17.setText(_translate("Form", "Label_17"))
        self.lab_2.setText(_translate("Form", "lab_2"))
        self.lab_5.setText(_translate("Form", "lab_5"))
        self.lab_8.setText(_translate("Form", "lab_8"))
        self.lab_1.setText(_translate("Form", "lab_1"))
        self.lab_3.setText(_translate("Form", "lab_3"))
        self.lab_4.setText(_translate("Form", "lab_4"))
        self.lab_6.setText(_translate("Form", "lab_6"))
        self.lab_9.setText(_translate("Form", "lab_9"))
        self.lab_7.setText(_translate("Form", "lab_7"))
        self.label_31.setText(_translate("Form", "Label_31"))
        self.label_34.setText(_translate("Form", "Label_34"))
        self.label_32.setText(_translate("Form", "Label_32"))
        self.label_35.setText(_translate("Form", "Label_35"))
        self.label_36.setText(_translate("Form", "Label_36"))
        self.label_33.setText(_translate("Form", "Labe_33"))
        self.label_37.setText(_translate("Form", "Label_37"))
        self.Label_20.setText(_translate("Form", " R1"))
        self.lab_12.setText(_translate("Form", "lab_12"))
        self.lab_15.setText(_translate("Form", "lab_15"))
        self.lab_18.setText(_translate("Form", "lab_18"))
        self.lab_13.setText(_translate("Form", "lab_13"))
        self.lab_11.setText(_translate("Form", "lab_11"))
        self.lab_14.setText(_translate("Form", "lab_14"))
        self.lab_16.setText(_translate("Form", "lab_16"))
        self.lab_17.setText(_translate("Form", "lab_17"))
        self.lab_19.setText(_translate("Form", "lab_19"))
        self.label_24.setText(_translate("Form", "Label_24"))
        self.label_21.setText(_translate("Form", "Label_21"))
        self.label_26.setText(_translate("Form", "Label_26"))
        self.label_25.setText(_translate("Form", "Label_25"))
        self.label_27.setText(_translate("Form", "Label_27"))
        self.label_22.setText(_translate("Form", "Label_22"))
        self.label_23.setText(_translate("Form", "Labe_23"))
        self.Label_19.setText(_translate("Form", " L3"))
        self.lab_32.setText(_translate("Form", "lab_32"))
        self.lab_31.setText(_translate("Form", "lab_31"))
        self.lab_33.setText(_translate("Form", "lab_33"))
        self.lab_34.setText(_translate("Form", "lab_34"))
        self.lab_37.setText(_translate("Form", "lab_37"))
        self.lab_36.setText(_translate("Form", "lab_36"))
        self.lab_35.setText(_translate("Form", "lab_35"))
        self.label_4.setText(_translate("Form", "Roof"))
        self.led_2.setText(_translate("Form", "led_2"))
        self.label.setText(_translate("Form", "      L"))
        self.led_1.setText(_translate("Form", "led_1"))
        self.led_3.setText(_translate("Form", "led_3"))
        self.label_5.setText(_translate("Form", "      R"))
        self.led_4.setText(_translate("Form", "led_4"))
        self.square_11.setText(_translate("Form", "square_11"))
        self.square_6.setText(_translate("Form", "square_6"))
        self.square_1.setText(_translate("Form", "square_1"))
        self.square_2.setText(_translate("Form", "square_2"))
        self.square_3.setText(_translate("Form", "square_3"))
        self.square_8.setText(_translate("Form", "square_8"))
        self.square_5.setText(_translate("Form", "square_5"))
        self.square_14.setText(_translate("Form", "square_14"))
        self.square_9.setText(_translate("Form", "square_9"))
        self.square_12.setText(_translate("Form", "square_12"))
        self.square_0.setText(_translate("Form", "square_0"))
        self.square_13.setText(_translate("Form", "square_013"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
