# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SkjermProg.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 376)
        self.Test2 = QtWidgets.QPushButton(Form)
        self.Test2.setGeometry(QtCore.QRect(140, 310, 111, 61))
        self.Test2.setObjectName("Test2")
        self.Test1 = QtWidgets.QPushButton(Form)
        self.Test1.setGeometry(QtCore.QRect(0, 310, 131, 61))
        self.Test1.setObjectName("Test1")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_01 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_01.setObjectName("label_01")
        self.gridLayout.addWidget(self.label_01, 1, 0, 1, 1)
        self.label_04 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_04.setObjectName("label_04")
        self.gridLayout.addWidget(self.label_04, 1, 2, 1, 1)
        self.label_02 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_02.setObjectName("label_02")
        self.gridLayout.addWidget(self.label_02, 2, 0, 1, 1)
        self.label_05 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_05.setObjectName("label_05")
        self.gridLayout.addWidget(self.label_05, 2, 2, 1, 1)
        self.label_06 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_06.setObjectName("label_06")
        self.gridLayout.addWidget(self.label_06, 3, 2, 1, 1)
        self.label_03 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_03.setObjectName("label_03")
        self.gridLayout.addWidget(self.label_03, 3, 0, 1, 1)
        self.label_07 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_07.setObjectName("label_07")
        self.gridLayout.addWidget(self.label_07, 3, 1, 1, 1)
        self.Label_08 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Label_08.setObjectName("Label_08")
        self.gridLayout.addWidget(self.Label_08, 2, 1, 1, 1)
        self.Test3 = QtWidgets.QPushButton(Form)
        self.Test3.setGeometry(QtCore.QRect(260, 310, 111, 61))
        self.Test3.setObjectName("Test3")
        self.Background = QtWidgets.QLabel(Form)
        self.Background.setEnabled(False)
        self.Background.setGeometry(QtCore.QRect(6, 2, 561, 391))
        self.Background.setObjectName("Background")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(290, 10, 281, 261))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 1, 1, 1)
        self.Label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Label_18.setObjectName("Label_18")
        self.gridLayout_2.addWidget(self.Label_18, 2, 1, 1, 1)
        self.Background.raise_()
        self.Test2.raise_()
        self.Test1.raise_()
        self.gridLayoutWidget.raise_()
        self.Test3.raise_()
        self.gridLayoutWidget_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Test2.setText(_translate("Form", "Test 2"))
        self.Test1.setText(_translate("Form", "Test 1"))
        self.label_01.setText(_translate("Form", "Label_01"))
        self.label_04.setText(_translate("Form", "Label_04"))
        self.label_02.setText(_translate("Form", "Label_02"))
        self.label_05.setText(_translate("Form", "Label_05"))
        self.label_06.setText(_translate("Form", "Label_06"))
        self.label_03.setText(_translate("Form", "Labe_03"))
        self.label_07.setText(_translate("Form", "Label_07"))
        self.Label_08.setText(_translate("Form", "Label_08"))
        self.Test3.setText(_translate("Form", "Test 3"))
        self.Background.setText(_translate("Form", "Background"))
        self.label_11.setText(_translate("Form", "Label_11"))
        self.label_14.setText(_translate("Form", "Label_14"))
        self.label_12.setText(_translate("Form", "Label_12"))
        self.label_15.setText(_translate("Form", "Label_15"))
        self.label_16.setText(_translate("Form", "Label_16"))
        self.label_13.setText(_translate("Form", "Labe_13"))
        self.label_17.setText(_translate("Form", "Label_17"))
        self.Label_18.setText(_translate("Form", "Label_18"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

